### ISSUE TITLE
Fan changing speed before dropping bellow med temperature

### ISSUE THREAD

**Issue by soloam** [khorton/nas_fan_control#4]
I think that something is wrong with the script! From what I see, if a CPU temp goes over "$high_cpu_temp" the fans go "high", and then should go "med" if droped bellow "med_cpu_temp". But from what I see, my fans go from "high" to "med" when temperature goes bellow "$high_cpu_temp", this makes the spinning very spiky. Going Full and low every few secconds:

DEBUG_LOG 2020-06-19 18:45:34: core_temp = 48.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 47.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 50.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 50.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 56.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 56.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:34: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:34: CPU Temp: 56.0
DEBUG_LOG 2020-06-19 18:45:34: CPU Temp: 56.0 >= 55, CPU Fan going high.
DEBUG_LOG 2020-06-19 18:45:34: CPU Fan: high
DEBUG_LOG 2020-06-19 18:45:34: CPU Fan changing... (high)
DEBUG_LOG 2020-06-19 18:45:34: Setting Zone 0 duty cycle to 100%
DEBUG_LOG 2020-06-19 18:45:35: core_temps:
53.0
53.0
54.0
55.0
53.0
53.0
51.0
55.0
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 55.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 51.0 C
DEBUG_LOG 2020-06-19 18:45:35: core_temp = 55.0 C
DEBUG_LOG 2020-06-19 18:45:35: CPU Temp: 55.0
DEBUG_LOG 2020-06-19 18:45:35: CPU Fan: high
DEBUG_LOG 2020-06-19 18:45:36: core_temps:
52.0
52.0
52.0
52.0
57.0
57.0
54.0
54.0
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 57.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 57.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:36: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:36: CPU Temp: 57.0
DEBUG_LOG 2020-06-19 18:45:36: CPU Fan: high
DEBUG_LOG 2020-06-19 18:45:39: core_temps:
52.0
52.0
53.0
53.0
60.0
59.0
55.0
55.0
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 60.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 59.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 55.0 C
DEBUG_LOG 2020-06-19 18:45:39: core_temp = 55.0 C
DEBUG_LOG 2020-06-19 18:45:39: CPU Temp: 60.0
DEBUG_LOG 2020-06-19 18:45:39: CPU Fan: high
DEBUG_LOG 2020-06-19 18:45:40: core_temps:
52.0
53.0
51.0
54.0
54.0
54.0
54.0
54.0
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 52.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 53.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 51.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:40: core_temp = 54.0 C
DEBUG_LOG 2020-06-19 18:45:40: CPU Temp: 54.0
DEBUG_LOG 2020-06-19 18:45:40: CPU Temp: 54.0 >= 45, CPU Fan going med.
DEBUG_LOG 2020-06-19 18:45:40: CPU Fan: med
DEBUG_LOG 2020-06-19 18:45:40: CPU Fan changing... (med)
DEBUG_LOG 2020-06-19 18:45:40: Setting Zone 0 duty cycle to 60%
DEBUG_LOG 2020-06-19 18:45:41: core_temps:

I think that should only go med when temperature is 45

**Comment by khorton** [comment]
Interesting.  Looking at the code that controls the CPU fan, the control loop will set the fan to MED once the CPU temp goes below $high_cpu_temp.  This is contrary to the wording of the comment in the CPU THRESHOLD TEMPS section.

Most of this script, including this portion, were slavishly copied from a script created by user @Stux, posted at https://forums.freenas.org/index.php?threads/script-hybrid-cpu-hd-fan-zone-controller.46159/.  I'll discuss this issue with him, to learn whether he intended it to work this way, and if so, why.  

It does seem logical that we would want some temperature hysteresis to avoid rapid cycling of the fan speed.

**Comment by soloam** [comment]
I changed the code and now it's working, I'll submit a change request to your validation! I'll do that during the weekend

**Comment by soloam** [comment]
To your consideration https://github.com/khorton/nas_fan_control/pull/5
